[tool.black]
preview = true
line-length = 130
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true

[tool.coverage.report]
# Exclude code that isn't ours
omit = ["*/site-packages/*","setup.py"]

# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if __version__ = .*",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    ]
