name: build

# Controls when the action will run. Triggers the workflow manually or on push or pull request
on:
  workflow_dispatch:

  push:
    # Only run the workflow for pushes to the following files
    paths:
      - '.github/workflows/build.yml'
      - '**/*.py'
    # Run on branches
    branches:
      - '**'
    # Don't run on tags
    tags:
      - '!**'
  pull_request:
    # Only run the workflow for requested changes to the following files
    paths:
      - '.github/workflows/build.yml'
      - '**/*.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job will run pylint on all python files
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pylint and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint setuptools pytest
      - name: Analyze the code with pylint
        run: pylint $(git ls-files '*.py')

  # This job will run the tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pylint and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Test the code
        run: coverage run -m project_name.my_module && coverage xml
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
