name: release

# Controls when the action will run. Triggers the workflow on push to tags only.
on:
  push:
    tags:
      - '*'
permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release" which publishes the python package
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      #- uses: jfrog/setup-jfrog-cli@v4
      #  id: jfrog-auth
      #  env:
      #      JF_URL: ${{ vars.JFROG_URL }}
      #  with:
      #      oidc-provider-name: ${{ secrets.JFROG_OIDC_PROVIDER_NAME }}
      #      oidc-audience: ${{ secrets.JFROG_OIDC_AUDIENCE }}
      #- name: Publish package
      #  uses: pypa/gh-action-pypi-publish@v1.8.10
      #  with:
      #    user: ${{ steps.jfrog-auth.outputs.oidc-user }}
      #    password: ${{ steps.jfrog-auth.outputs.oidc-token }}
      #    repository-url: ${{ vars.PYPI_REPO_URL }}
      #- name: Publish Build info With JFrog CLI
      #  run: |
      #   # Collect environment variables for the build
      #   jf rt build-collect-env
      #   # Collect VCS details from git and add them to the build
      #   jf rt build-add-git
      #   # Publish build info
      #   jf rt build-publish
